### ISSUE TITLE
Help button is shown even when disabled

### ISSUE THREAD

**Issue by Caster** [makyen/StackExchange-userscripts#2]
When I disable the *Add the help button if it's not already displayed.* checkbox, the help button disappears from the navigation. However, upon navigating to any other page, or simply reloading, the help button reappears. I have enough reputation to not normally see the help button.

Help? :slightly_smiling_face:

**Comment by kayesshu** [comment]
I can confirm and repro this.

**Comment by makyen** [comment]
Thanks for the report. Fixed in version 1.0.1.
