### ISSUE TITLE
...

### ISSUE THREAD

**Issue by GolfingSuccess** [makyen/StackExchange-userscripts#27]
Roomba Forecaster currently shows this:

![untitled](https://user-images.githubusercontent.com/19519588/50336284-77de7d80-0516-11e9-8981-d35dbe1b3a14.png)

You can go here to reproduce this issue:

https://codegolf.stackexchange.com/q/177784/41024

Note: I think there has been yet another redesign on SE, and the issue appeared at the same time I saw the redesign.

**Comment by makyen** [comment]
Thanks for reporting the problem.
