### ISSUE TITLE
The anti follow popup script fails with "'$' is not defined"

### ISSUE THREAD

**Issue by ComFreek** [makyen/StackExchange-userscripts#37]
> Execution of script 'SE: Dismiss New Follow Feature Popup On Active Sites' failed! '$' is not defined

Browser: Micrsofot Edge with TamperMonkey

I am afraid I cannot give an accurate line number as apparently TamperMonkey interferes with this and the line numbers reported in the dev console are meaningless.

**Comment by makyen** [comment]
I didn't specifically duplicate the issue you had in Edge (i.e. it worked fine for me). However, I made the userscript significantly more compatible across browsers and different userscript managers. If version 1.1.0 doesn't resolve the problem you were experiencing, please leave a comment here and reopen this issue.
