### ISSUE TITLE
Roomba forecaster sometimes gets a 404

### ISSUE THREAD

**Issue by tripleee** [makyen/StackExchange-userscripts#45]
I'm just the messenger here, really. Discussion in SOCVR here:

https://chat.stackoverflow.com/transcript/message/54622002#54622002

There's an allegation that the filter in the API query is causing a problem.

**Comment by cristik** [comment]
A failure sample:

- question: https://stackoverflow.com/questions/72276703/bootstrap-carousel-not-changing-image
- problematic request: https://api.stackexchange.com/2.2/questions/72276703?site=stackoverflow.com&filter=!b0OfMvgVcFN2Ro&key=ZCNbdLB0bpKnf4EjSy8bdQ((
- console log error: 
```
userscript.html?name=Roomba%2520Forecaster.user.js&id=f1754200-c65d-404d-8d68-bf19aa8a9bbc:723          GET https://api.stackexchange.com/2.2/questions/72276703?site=stackoverflow.com&filter=!b0OfMvgVcFN2Ro&key=ZCNbdLB0bpKnf4EjSy8bdQ(( 400 (Bad Request)
```
![Screenshot 2022-05-24 at 08 48 11](https://user-images.githubusercontent.com/649286/169958045-8ffc19a6-e388-4fab-9a24-05f41ce2a0f3.png)

Server response:
```
{"error_id":404,"error_message":"no method found with this name","error_name":"no_method"}
```

**Comment by HenryEcker** [comment]
My belief that it may be filter related stems from the fact that the request made by the script script for [this question](https://stackoverflow.com/q/72303483) 

https://api.stackexchange.com/2.2/questions/72303483?site=stackoverflow.com&filter=!b0OfMvgVcFN2Ro&key=ZCNbdLB0bpKnf4EjSy8bdQ((  

produces:
```json
{
  "error_id": 404,
  "error_message": "no method found with this name",
  "error_name": "no_method"
}
```
While removing the filter 

https://api.stackexchange.com/2.2/questions/72303483?site=stackoverflow.com&key=ZCNbdLB0bpKnf4EjSy8bdQ(( 

returns:

```json
{
  "items": [
    {
      "tags": [
        "python",
        "matlab"
      ],
      "owner": {
        "reputation": 1,
        "user_id": 19152768,
        "user_type": "registered",
        "profile_image": "https://www.gravatar.com/avatar/570b3da243fc18dd16fa7a9ce702daae?s=256&d=identicon&r=PG",
        "display_name": "Stephane",
        "link": "https://stackoverflow.com/users/19152768/stephane"
      },
      "is_answered": false,
      "view_count": 39,
      "closed_date": 1652963992,
      "answer_count": 0,
      "score": -4,
      "last_activity_date": 1652958567,
      "creation_date": 1652958567,
      "question_id": 72303483,
      "link": "https://stackoverflow.com/questions/72303483/function-tf2sos-in-python-does-not-return-same-outputs-as-matlab-s-tf2sos",
      "closed_reason": "Not suitable for this site",
      "title": "Function “tf2sos” in python, does NOT return same outputs as matlab’s tf2sos"
    }
  ],
  "has_more": false,
  "quota_max": 10000,
  "quota_remaining": 9765
}
```

**Comment by codygray** [comment]
Bug report posted by Ryan M to MSE: https://meta.stackexchange.com/questions/378964/many-api-requests-to-questions-with-filter-parameters-are-failing-with-status-c

**Comment by tripleee** [comment]
https://chat.stackoverflow.com/transcript/message/54623877#54623877
